name: Deploy Angular al VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Compilar proyecto (Build Production)
        run: npm run build -- --configuration=production

      - name: Comprimir archivos compilados
        run: tar -czf frontend.tar.gz -C dist/Inventario-ai/browser .

      - name: Subir archivo comprimido al VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "frontend.tar.gz"
          target: "/var/www/seminario1/sgp/"

      - name: Limpiar, descomprimir y dejar listo en VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            # 1. Mover el archivo subido a la carpeta /tmp del sistema para operar de forma segura
            mv /var/www/seminario1/sgp/frontend.tar.gz /tmp/frontend.tar.gz

            # 2. Vaciar por completo la carpeta de producción sin salir de ella ni usar rutas relativas peligrosas
            rm -rf /var/www/seminario1/sgp/*

            # 3. Descomprimir el contenido directamente en la carpeta destino
            tar -xzf /tmp/frontend.tar.gz -C /var/www/seminario1/sgp/

            # 4. Eliminar el archivo comprimido temporal del servidor
            rm /tmp/frontend.tar.gz
