name: Deploy Angular al VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Compilar proyecto (Build Production)
        run: npm run build -- --configuration=production

      - name: Comprimir archivos compilados
        run: tar -czf frontend.tar.gz -C dist/Inventario-ai/browser .

      - name: Configurar llave SSH temporal
        env:
          # Pasamos el secreto como variable de entorno para proteger los caracteres especiales
          SSH_KEY_ENV: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh

          # Guardamos la variable de entorno directamente usando un Heredoc limpio
          cat << 'EOF' > ~/.ssh/id_ed25519
          $SSH_KEY_ENV
          EOF

          chmod 600 ~/.ssh/id_ed25519
          # Escanea el servidor para agregarlo a los hosts conocidos
          ssh-keyscan -p 22 -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Subir archivo comprimido al VPS (Nativo)
        run: |
          scp -P 22 -i ~/.ssh/id_ed25519 frontend.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/seminario1/sgp/

      - name: Limpiar, descomprimir y dejar listo en VPS (Nativo)
        run: |
          ssh -p 22 -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e

            # 1. Mover el archivo subido a la carpeta /tmp de forma segura
            mv /var/www/seminario1/sgp/frontend.tar.gz /tmp/frontend.tar.gz

            # 2. Limpiar la carpeta de producción de la app de Angular
            rm -rf /var/www/seminario1/sgp/*

            # 3. Descomprimir el nuevo build en la ruta destino
            tar -xzf /tmp/frontend.tar.gz -C /var/www/seminario1/sgp/

            # 4. Eliminar el archivo temporal comprimido
            rm /tmp/frontend.tar.gz
          EOF
