name: Deploy Angular al VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4 # Actualizado a v4
        with:
          node-version: '20' # Usamos una versión estable y moderna
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install # Cambiado por npm install para evitar el exit code 3

      - name: Compilar proyecto (Build Production)
        run: npm run build -- --configuration=production

      - name: Transferir archivos compilados al VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/Inventario-ai/browser/*" 
          target: "/var/www/seminario1/sgp/"
          strip_components: 3